---
- hosts: all


     

  # tasks file for dhcp
  vars_files:
    - vars/main.yml

  # roles:
  #   -  {role: ansible-network-gateway,  when: '"clark-gateway" in inventory_hostname'}
  #     # when: "{{inventory_hostname }}in {{ groups['clark-gateway'] }} "
     


  tasks:

  - name: Find NICs 
    when: "{{ 'clark-dhcp' in inventory_hostname }}"
    ansible.builtin.debug:
      msg: "{{ ansible_facts[item]['macaddress']|default(None) }}"
    with_items:
    - "{{ ansible_interfaces }}"
   
      
    - name: Retrieve host vars
      debug:
        msg: "{{ ansible_interfaces | difference(['lo']) | map('regex_replace', '^(.*)$', 'ansible_\\1' ) | map('extract', hostvars[inventory_hostname], 'macaddress')  | list }}"
      when: "{{ 'clark-dhcp' in inventory_hostname }}"



# data:
#   - name: gateway
#     ip: 10.0.0.1
#     ip_out: 192.168.1.100
#     mac_address: 0:50:56:87:79:f3
#     interface_in_name: ens224
#     interface_out_name: ens192
#   - name: dhcp
#     ip: 10.0.0.2
#     mac_address: 0:50:56:87:79:f3
#     interface_in_name: ens224
#     interface_out_name: ens192
#   - name: dns
#     ip: 10.0.0.3
#     mac_address: 0:50:56:87:79:f3
#     interface_in_name: ens224
#     interface_out_name: ens192









    # - name: run dhcp task file
    #   include_tasks: tasks/main.yml
    #   when: "{{ 'clark-dhcp' in inventory_hostname }}"


  # - name: gateway
  #   ansible.builtin.include_role:
  #     name: ansible-network-gateway
  #   when: "'gateway' in {{ hosts_vars }}"



# - name: run dhcp
#   ansible.builtin.include: dhcp.yml
#   when: "'dhcp' in {{ hosts_vars }}"




