---
- hosts: all

     

  # tasks file for dhcp
  vars_files:
    - vars/main.yml

  # roles:
  #   -  {role: ansible-network-gateway,  when: '"clark-gateway" in inventory_hostname'}
  #     # when: "{{inventory_hostname }}in {{ groups['clark-gateway'] }} "
     


  tasks:
  - name: interface_out_name for dhcp
    when: "{{ 'clark-dhcp' in inventory_hostname }}"
    ansible.builtin.debug:
      msg: "{{ ansible_facts.interfaces[1] }}"

  - name: interface_out_name for dhcp
    when: "{{ 'clark-dhcp' in inventory_hostname }}"
    ansible.builtin.debug:
      msg: "{{ ansible_facts.interfaces[2] }}"

  - name: ip for dhcp in
    when: "{{ 'clark-dhcp' in inventory_hostname }}"
    ansible.builtin.debug:
      msg: "{{ ansible_facts[data[1].interface_in_name]['ipv4'].address }}"

  - name: mac_address for dhcp in
    when: "{{ 'clark-dhcp' in inventory_hostname }}"
    ansible.builtin.debug:
      msg: "{{ ansible_facts[data[1].interface_in_name]['macaddress']|default(None) }}"





  # - name: mac_address for dhcp in
  #   ansible.builtin.debug:
  #     msg: "{{ data  }}"
      

   

  # - name: adding foward zone and back zone to named.conf
  #   ansible.builtin.blockinfile:
  #     insertafter: EOF
  #     create: yes
  #     marker: "// from ansible"
  #     path: /test.txt
  #     block: |
  #         {{ data[0].interface_in_name }}



      
#      msg: "{{ ansible_facts[item]['macaddress']|default(None) }}"

# data:
#   - name: gateway
#     ip: 10.0.0.1
#     ip_out: 192.168.1.100
#     mac_address: 0:50:56:87:79:f3 
#     interface_in_name: ens224
#     interface_out_name: ens192
#   - name: dhcp
#     ip: 10.0.0.2 //
#     mac_address: 0:50:56:87:79:f3 //
#     interface_in_name: ens224 //
#     interface_out_name: ens192 //
#   - name: dns
#     ip: 10.0.0.3
#     mac_address: 0:50:56:87:79:f3 
#     interface_in_name: ens224
#     interface_out_name: ens192









    # - name: run dhcp task file
    #   include_tasks: tasks/main.yml
    #   when: "{{ 'clark-dhcp' in inventory_hostname }}"


  # - name: gateway
  #   ansible.builtin.include_role:
  #     name: ansible-network-gateway
  #   when: "'gateway' in {{ hosts_vars }}"



# - name: run dhcp
#   ansible.builtin.include: dhcp.yml
#   when: "'dhcp' in {{ hosts_vars }}"




