---


# tasks file for dhcp

  # - name: Print all available facts
  #   ansible.builtin.debug:
  #     var: ansible_facts



- name: gateway
  hosts: clark-gateway
  roles:
    - ansible-network-gateway



- name: run dhcp
  ansible.builtin.include_tasks: dhcp.yml